### ISSUE TITLE
Calendar respond with 404

### ISSUE THREAD

**Issue by iHDeveloper** [InventivetalentDev/HypixelAPI#10]
[API](https://hypixel-api.inventivetalent.org/api/skyblock/calendar) respond with not found `404`

## What steps will reproduce the problem?  
1. Open [UI](https://hypixel.inventivetalent.org/skyblock-calendar/)
2. The calendar will be empty and doesn't have any event on it.

Or
1. Open [API](https://hypixel-api.inventivetalent.org/api/skyblock/calendar)
2. It will respond with `Cannot GET /api/skyblock/calendar `

## What were you expecting to happen? What happened instead?  
The [API](https://hypixel-api.inventivetalent.org/api/skyblock/calendar) is expected to return results about the **Skyblock** calendar.

**Comment by iHDeveloper** [comment]
According to my logs, the issue started to appear since **8/14/2020**.

**Comment by InventivetalentDev** [comment]
Looks like the wrong version of a file snuck into the upload, should be fixed now c:
